spring.datasource.username=${DB_USERNAME:jobportal}
spring.datasource.password=${DB_PASSWORD:jobportal}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jobportal}

server.port=${PORT:8080}
server.tomcat.max-part-count=50
